name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]

permissions:
  contents: write


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Node.js ⚙️
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies 🔧
        # Chuyển vào thư mục shadcn-ui trước khi cài đặt
        working-directory: ./shadcn-ui
        run: pnpm install

      - name: Build 🏗️
        working-directory: ./shadcn-ui
        run: pnpm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # Thư mục build nằm trong shadcn-ui/dist
          folder: shadcn-ui/dist
          branch: gh-pages
